## Problem Statement: Customer Segmentation Using K-Means Clustering

Objective: The goal is to segment the customers into different groups based on their purchasing behavior and demographics using the K-means clustering algorithm. This will help the store target different customer groups with tailored marketing strategies.

## import libraries

In [7]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans

In [8]:
df = pd.read_csv('customer_data.csv')

In [9]:
df.head()

   CustomerID  Age  Annual Income (k$)  Spending Score (1-100)  Gender
0           1   56                  96                      61  Female
1           2   69                  77                      77  Female
2           3   46                 119                      51  Female
3           4   32                  71                      50    Male
4           5   60                 150                      19  Female

## preprocessing

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 5 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   CustomerID              5000 non-null   int64
 1   Age                     5000 non-null   int64
 2   Annual Income (k$)      5000 non-null   int64
 3   Spending Score (1-100)  5000 non-null   int64
 4   Gender                  5000 non-null   object
dtypes: int64(4), object(1)
memory usage: 195.4+ KB

No missing values, all columns are of int type

In [12]:
df["Gender"] =  df["Gender"].map({"Female":0, "Male":1})

In [13]:
df.head()

   CustomerID  Age  Annual Income (k$)  Spending Score (1-100)  Gender
0           1   56                  96                      61       0
1           2   69                  77                      77       0
2           3   46                 119                      51       0
3           4   32                  71                      50       1
4           5   60                 150                      19       0

In [14]:
features = df[['Age', 'Annual Income (k$)', 'Spending Score (1-100)']]
features_scaled = StandardScaler().fit_transform(features)

In [15]:
features_scaled

array([[ 0.78024596,  0.33701889,  0.36693116],
       [ 1.63485615, -0.15195883,  0.92465146],
       [ 0.1228535 ,  0.92893929,  0.01835597],
       ...,
       [-0.46879971, -1.07844294, -1.23651471],
       [ 0.1228535 ,  0.02819085, -1.20165719],
       [-0.20584273,  1.03188196, -1.68966245]])

## EDA

AttributeError: module 'matplotlib.pyplot' has no attribute 'scaler'